[package]
name = "mello"
description = "A small toolbox for fast web api prototyping"
authors = ["Mattia Penati <mattia.penati@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = { version = "1.0.81", optional = true }
once_cell = { version = "1.19.0", optional = true, features = ["parking_lot"] }
parking_lot = { version = "0.12.1", optional = true }
rusqlite = { version = "0.31.0", optional = true }
serde = { version = "1.0.197", optional = true, features = ["derive"] }
serde_json = { version = "1.0.114", optional = true }
thread_local = { version = "1.1.8", optional = true }
tracing = { version = "0.1.40", optional = true }

[dependencies.tracing-appender]
version = "0.2.3"
optional = true
features = ["parking_lot"]

[dependencies.tracing-subscriber]
version = "0.3.18"
optional = true
default-features = false
features = ["ansi", "env-filter", "fmt", "parking_lot", "time", "tracing-log"]

[dev-dependencies]
claym = "0.5.1"

[features]
kvstorage = [
  "dep:anyhow",
  "dep:parking_lot",
  "dep:rusqlite",
  "dep:serde",
  "dep:serde_json",
  "dep:thread_local",
]
trace = [
  "dep:anyhow",
  "dep:once_cell",
  "dep:serde",
  "dep:tracing",
  "dep:tracing-appender",
  "dep:tracing-subscriber",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
