[package]
name = "mello"
description = "A small toolbox for fast web api prototyping"
authors = ["Mattia Penati <mattia.penati@protonmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
parking_lot = "0.12.1"
rusqlite = "0.31.0"
serde = "1.0.197"
serde_json = "1.0.114"
thread_local = "1.1.8"

[dev-dependencies]
claym = "0.5.1"
