[package]
name = "mello"
description = "A small toolbox for fast web api prototyping"
authors = ["Mattia Penati <mattia.penati@protonmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.81", optional = true }
parking_lot = { version = "0.12.1", optional = true }
rusqlite = { version = "0.31.0", optional = true }
serde = { version = "1.0.197", optional = true }
serde_json = { version = "1.0.114", optional = true }
thread_local = { version = "1.1.8", optional = true }

[dev-dependencies]
claym = "0.5.1"

[features]
kvstorage = [
  "dep:anyhow",
  "dep:parking_lot",
  "dep:rusqlite",
  "dep:serde",
  "dep:serde_json",
  "dep:thread_local",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
