[package]
name = "mello"
description = "A small toolbox for fast web api prototyping"
authors = ["Mattia Penati <mattia.penati@protonmail.com>"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
bytes = "1.6.0"
http = "1.1.0"
hyper = { version = "1.2.0", features = ["client", "http1"] }
hyper-util = { version = "0.1.3", features = ["tokio"] }
num_cpus = "1.16.0"
once_cell = { version = "1.19.0", optional = true }
parking_lot = "0.12.1"
pin-project-lite = "0.2.14"
rusqlite = { version = "0.31.0", optional = true }
serde = { version = "1.0.197", optional = true, features = ["derive"] }
serde_json = { version = "1.0.115", optional = true }
slab = "0.4.9"
thread_local = { version = "1.1.8", optional = true }
tower-service = "0.3.2"
tower-layer = "0.3.2"
tracing = "0.1.40"
tracing-opentelemetry = { version = "0.23.0", default-features = false }
opentelemetry = { version = "0.22.0", default-features = false }


[dependencies.tokio]
version = "1.37.0"
features = ["io-util", "net", "sync", "rt"]

[dependencies.tracing-appender]
version = "0.2.3"
optional = true
features = ["parking_lot"]

[dependencies.tracing-subscriber]
version = "0.3.18"
optional = true
default-features = false
features = ["ansi", "env-filter", "fmt", "parking_lot", "time", "tracing-log"]

[dev-dependencies]
claym = "0.5.1"

[features]
kvstorage = ["dep:rusqlite", "dep:serde", "dep:serde_json", "dep:thread_local"]
trace = [
  "dep:once_cell",
  "dep:serde",
  "dep:tracing-appender",
  "dep:tracing-subscriber",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
